### ISSUE TITLE
text colors and scaling

### ISSUE THREAD

**Issue by nottooloud** [bstaple1/MTGA_Draft_17Lands#15]
Mac M1 Mini with a 4k monitor. Text colors mostly seem to be white on white, so that the settings window appears totally blank. Text shows if I click on it. Text in general is tiny. Is there a way to scale it up?

**Comment by bstaple1** [comment]
Hi nottooloud,

Could you open your terminal, enter the following commands, and send me the results?

![image](https://user-images.githubusercontent.com/96687942/188722134-337f5390-c9e1-4f4b-a9c3-5a5da3435e2a.png)

Replace _python_ with _python3.10_.

**Comment by bstaple1** [comment]
Build 3.03 has two modifications that were added to address this ticket:
- The application/text scaling can be adjusted by changing the scale_factor field in the config.json file
- The dark mode theme (dark_mode.tcl) was removed for Mac in case it was conflicting with the OSX light/dark modes

I don't have access to an M1 computer or a 4K monitor, however, I've tested these changes on a non-M1 Mac and I've confirmed that there are no issues. 

I will leave this ticket open for a couple of days so that this user, or any other users with a similar issue, can provide feedback.

**Comment by nottooloud** [comment]
Fails to run, no module named numpy.

Dan

**Comment by nottooloud** [comment]
My bad, missed the new requirements_mac txt.

Text colors all fixed, size still small. Is there a setting for scaling?

Dan

**Comment by bstaple1** [comment]
Increase the scale_factor value in the config.json file

**Comment by nottooloud** [comment]
Last login: Tue Sep  6 08:23:05 on console
***@***.*** ~ % python3.10
Python 3.10.4 (v3.10.4:9d38120e33, Mar 23 2022, 17:29:05) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import tkinter
>>> tcl = tkinter.Tcl()
>>> tcl.call("info","patchlevel")
'8.6.12'
>>> root = tkinter.Tk()
>>> root.winfo_fpixels('1i')
71.98228782287823
>>>
