### ISSUE TITLE
App is not recognizing that I'm in a draft

### ISSUE THREAD

**Issue by Phyrre56** [bstaple1/MTGA_Draft_17Lands#27]
Just upgraded to 3.07. Started a Shadows Remastered Premier Draft. When I opened the Magic Draft app, it said Current Draft: None. No recognition that I was drafting at all. The draft that I did shows up in 17lands so it was being recorded by the draft log. This is the 2nd time this has happened. Any ideas?

**Comment by bstaple1** [comment]
Hi Phyrre56,

Have you tried the solution listed in the [troubleshooting section of the readme?](https://github.com/bstaple1/MTGA_Draft_17Lands/blob/main/README.md#troubleshooting)

**Comment by Phyrre56** [comment]
I did try the solution in the readme, but the app using the regular .exe also started working fine again. It seems to be a transient issue, only pops up occasionally. Next time I'm going to try restarting the computer or something and see if it fixes it, or if specific events for some reason seem to break it. (It's not format specific though, it happened once with a ONE draft and then was fine for the next ONE draft, and the same with SIR.)

**Comment by bstaple1** [comment]
I tried to reproduce your issue by starting a SIR draft, opening and closing the application, and modifying the settings mid-draft. The application was able to detect the draft every time and I didn't see any issues.

Is the application still unable to detect a draft after you restart it? 

The next time this happens, if you could send me your Player.log file and debug.log files, then I can look into this further. Since I can't reproduce this issue on my own, there isn't much I can do without the log files.
