### ISSUE TITLE
Feature request: compare player tiers

### ISSUE THREAD

**Issue by gpofcher** [bstaple1/MTGA_Draft_17Lands#35]
It would be awesome to be able to see how a card's performance compares across the player tiers.

I'm most interested in a comparison of how frequently different tiers play a card in their deck, but differences in GIHWR, ATA, and ratio of number seen / picked would also be great to have access to.

**Comment by bstaple1** [comment]
Hi gpofcher, thank you for your interest in this project.

Are you referring to the user performance groups on the 17Lands card performance page (Top/Middle/Bottom/All Users) when you mention player tiers? If that's the case, then we might have trouble with rate limiting if we need to collect four sets of data for all of the deck filters.

Do you have any thoughts on how we would convey this information in the overlay? This overlay should fit in the left margin of the Arena draft screen without obstructing the view of the cards, so space is highly limited.

**Comment by gpofcher** [comment]
Yeah, I guess user performance groups is the technical term.

I hadn't realized that each combination of colors and performance group would require a separate download. That does sound like a lot.

As far as displaying the data... maybe mousing over a stat in the overlay could activate a tooltip with the top/middle/bottom stats?

I wonder if both problems could be solved by only making this information available in the picked cards and deck suggestion windows, after the draft is complete. That would limit the number of color combinations needed, and allow for using up more space.

**Comment by Gbriel** [comment]
I too would be interested in viewing data separated by user performance tiers. In my case however, I'm really just interested in seeing the GIH WR for top tier players, as that happens to be a (much) more useful measure for me than overall. 
For instance, a situational card might have a low overall WR because lower tier players just throw it in their deck, while it might have a very high WR for top tier because they are playing it in the correct situations.
